# Generated by Django 4.2.17 on 2025-02-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallerymedia_projectmedia_delete_galleryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery_media/'),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_media/'),
        ),
    ]
