# Generated by Django 4.2.17 on 2025-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_gallerymedia_file_alter_projectmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerymedia',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryupload',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
